1.6.0

diff --git a/sbin/decipher-install b/sbin/decipher-install
--- a/sbin/decipher-install
+++ b/sbin/decipher-install
@@ -1,4 +1,4 @@
-#!/bin/csh -f
+#!/bin/sh
 #
 #    File:   decipher-install
 #    Author: Tom Kuhn (original by Victor Abrash)
@@ -12,177 +12,135 @@
 #
 #		decipher-install <mode> <file1> ... <fileN> <directory>
 #
-#    Copyright (c) 1994, SRI International.  All Rights Reserved.
+#    Copyright (c) 1994-2011 SRI International.  All Rights Reserved.
 #
-#    RCS ID: $Id: decipher-install,v 1.7 2009/10/05 18:41:22 stolcke Exp $
-#
-#    $Log: decipher-install,v $
-#    Revision 1.7  2009/10/05 18:41:22  stolcke
-#    added -p option to preserve times
-#
-#    Revision 1.6  2009/05/22 17:45:53  stolcke
-#    relaxed constraint on mode bits
-#
-#    Revision 1.5  2007/01/26 07:34:09  stolcke
-#    manifest hack no longer required
-#
-#    Revision 1.4  2007/01/25 18:22:27  stolcke
-#    install .manifest files generated by MSVC
-#
-#    Revision 1.3  2000/06/08 18:30:31  stolcke
-#    backup recently used executables before installing new version
-#
-#    Revision 1.2  2000/06/08 17:51:18  stolcke
-#    avoid ginstall and decipher-specific stuff
-#
-#    Revision 1.4  1995/02/22 01:46:58  tmk
-#    Updates from Andreas' Solaris port
-#
-# Revision 1.3  1994/12/03  23:54:44  decipher
-# Reorganized the error checking so usage message wasn't always printed.
-#
-# Revision 1.2  1994/11/24  01:47:35  decipher
-#  Revised to take variable number of arguments.  Now uses ginstall instead
-# of each platforms' local install.  More error checking added.
-#
-# Revision 1.1  1994/08/26  22:24:38  victor
-# Initial revision
-#
+#    RCS ID: $Id: decipher-install,v 1.8 2011/10/21 21:25:58 stolcke Exp $
 #
 
 # By using this flag, the script runs through all error checking and
 # reports all errors before exiting
-unset error
+error=
 
-# Set these variables now so diagnostic printing on errors works nicely
-set FILES DIR MODE
-
-# this script can only be run by decipher:
-#if (`whoami` != decipher) then
-#	echo "ERROR:  installation must be done by user 'decipher'."
-#	exit -1
-#endif
-
-if ( "$1" == "-p" ) then
-	set p_option = -p
+if [ "$1" = -p ]; then
+	p_option=-p
 	shift
-else
-	set p_option = ""
-endif
+fi
+
+usage() {
+    echo "Usage:  `basename $0` [-p] <mode> <file1> ... <fileN> <directory>"	>&2
+    echo "	mode:                 file permission mode, in octal"		>&2
+    echo "	file1 ... fileN:      files to be installed"			>&2
+    echo "	directory:            where the files should be installed"	>&2
+    echo ""									>&2
+    echo "files = " $FILES							>&2
+    echo "directory = " $DIR							>&2
+    echo "mode = " $MODE							>&2
+    echo ""									>&2
+    exit 1
+}
 
 # Get the arguments, check usage.  Have to bail completely if there
 # aren't enough arguments.
-if ($#argv < 3) then
-	echo "WARNING:  There are arguments missing"
+if [ $# -lt 3 ]; then
+	usage
 	exit -1
-endif
+fi
 
-set MODE = $1
+MODE=$1
 shift
 
-set DIR  = $argv[$#argv]
+FILES=
 
-while ($#argv > 1) 
-	set FILES = ($FILES $1)
+while [ $# -gt 1 ]; do
+	FILES="$FILES $1"
 	shift
-end
+done
+
+DIR=$1
 
 # we should check that these are valid:
 # First, check the mode
-if ($MODE !~ 0[1-7][0-7][0-7]) then
-	echo "ERROR: Mode ($MODE) is not a valid permission setting"
-	set error
-endif
+case "$MODE" in
+0[1-7][0-7][0-7]) ;;
+*)	echo "ERROR: Mode ($MODE) is not a valid permission setting"	>&2
+	exit 1
+esac
 
 # Now check each file
-foreach FILE ($FILES)
-   if (! -e ${FILE}) then
-      echo "ERROR:  File to be installed (${FILE}) does not exist."
-      set error
-   endif
-   if (-z ${FILE}) then
-      echo "ERROR:  File to be installed (${FILE}) is zero length."
-      set error
-   endif
-   if (! -f ${FILE}) then
-      echo "ERROR:  File to be installed (${FILE}) is not a plain file."
-      set error
-   endif
-end
+for file in $FILES
+do
+   if [ ! -f $file ]; then
+      echo "ERROR:  File to be installed ($file) does not exist."	>&2
+      error=1
+   elif [ -z $file ]; then
+      echo "ERROR:  File to be installed ($file) is zero length."	>&2
+      error=1
+   elif [ ! -f $file ]; then
+      echo "ERROR:  File to be installed ($file) is not a plain file."	>&2
+      error=1
+   fi
+done
 
-if (! -d ${DIR}) then
-   echo "WARNING: creating directory ${DIR}"
+if [ ! -d $DIR ]; then
+   echo "WARNING: creating directory ${DIR}"	>&2
    mkdir ${DIR}
-endif
+fi
 
 # Now check the directory
-if (! -e ${DIR}) then
-   echo "ERROR:  Installation directory (${DIR}) does not exist."
-   set error
-endif
-if (! -d ${DIR}) then
-   echo "ERROR:  Installation target (${DIR}) is not a directory."
-   set error
-endif
-if (! -w ${DIR}) then
-   echo "ERROR:  Don't have write permission in installation directory (${DIR})."
-   set error
-endif
+if [ ! -d $DIR ]; then
+   echo "ERROR:  Installation directory ($DIR) does not exist or is not a directory."	>&2
+   error=1
+elif [ ! -w $DIR ]; then
+   echo "ERROR:  Don't have write permission in installation directory ($DIR)."	>&2
+   error=1
+fi
 
 # check that $DIR is a valid destination: 
 # currently, this means we should be able to install files under
 # /include, /bin/, and /lib/ directories under /home/decipher:
 
-#@@ Get rid of '^' in egrep so /tmp_mnt prefix from NFS ok.
-#if (`echo ${DIR} | egrep '\/home\/decipher'` == "") then
-#   echo "ERROR:  You can install files only under /home/decipher"
-#   set error
-#endif
-
-if (`echo ${DIR} | egrep '\/bin|\/include|\/lib\/'` == "") then
-   echo "ERROR:  You can install files only in .../include, .../bin/, or .../lib/ directories."
-   set error
-endif
+case "$DIR" in
+*/bin|*/bin/*|*/include|*/lib/*)	;;
+*)
+   echo "ERROR:  You can install files only in .../include, .../bin/, or .../lib/ directories."	>&2
+   error=1
+   ;;
+esac
 
 # Bail out if there have been errors:
-if ($?error) goto USAGE
+if [ -n "$error" ]; then
+    usage
+fi
 
 # Install the files:
 
 #echo "ginstall -p -m ${MODE} ${FILES} ${DIR}"
 #ginstall -p -m ${MODE} ${FILES} ${DIR} 
-foreach file (${FILES})
-	set base = `basename $file`
+
+for file in $FILES
+do
+	base=`basename $file`
 
 	# remove executable backups not accessed in one day
-	foreach file2 ( `find ${DIR} -name "$base.~[0-9]*" -perm -0500 -atime +1 -print` )
-		echo "removing old backup $file2"
-		rm -f $file2
-	end
+	find $DIR -name "$base.~[0-9]*" -perm -0500 -atime +1 -print | \
+	while read file2
+	do
+	    echo "removing old backup $file2"
+	    rm -f $file2
+	done
 
 	# backup executables accessed within the last day
-	foreach file2 ( `find ${DIR} -name $base -perm -0500 -atime -1 -print` )
-		echo "$file2 is in use; backing up to $file2.~$$"
-		mv $file2 $file2.~$$
-	end
+	find $DIR -name $base -perm -0500 -atime -1 -print | \
+	while read file2
+	do
+	    echo "$file2 is in use; backing up to $file2.~$$"
+	    mv $file2 $file2.~$$
+	done
 
-	rm -f ${DIR}/$base
-	cp $p_option $file ${DIR}
-	chmod ${MODE} ${DIR}/$base
-end
+	rm -f $DIR/$base
+	cp $p_option $file $DIR
+	chmod $MODE $DIR/$base
+done
 
-# exit:
 exit 0
 
-USAGE:
-
-echo "Usage:  "`basename ${0}`" <mode> <file1> ... <fileN> <directory>"
-echo "	mode:                 file permission mode, in octal"
-echo "	file1 ... fileN:      files to be installed"
-echo "	directory:            where the files should be installed"
-echo ""
-echo "files = " $FILES
-echo "directory = " $DIR
-echo "mode = " $MODE
-echo ""
-exit 1
diff --git a/sbin/machine-type b/sbin/machine-type
--- a/sbin/machine-type
+++ b/sbin/machine-type
@@ -1,4 +1,4 @@
-#!/bin/csh -f
+#!/bin/sh
 #
 #    File:   machine-type
 #    Author: The SRI DECIPHER (TM) System
@@ -11,47 +11,9 @@
 #      identity. (Based on the Corona script of the same name)
 #
 #
-#    Copyright (c) 1995, SRI International.  All Rights Reserved.
+#    Copyright (c) 1995-2011 SRI International.  All Rights Reserved.
 #
-#    RCS ID: $Id: machine-type,v 1.10 2006/03/04 06:25:37 stolcke Exp $
-#
-#    $Log: machine-type,v $
-#    Revision 1.10  2006/03/04 06:25:37  stolcke
-#    return i686 on x86_64 machines
-#
-#    Revision 1.9  2005/09/30 22:55:35  stolcke
-#    support x86_64 platform
-#
-#    Revision 1.8  2005/09/20 04:47:36  stolcke
-#    support ppc64
-#
-#    Revision 1.7  2003/04/19 16:57:36  stolcke
-#    freebsd support
-#
-#    Revision 1.6  2003/02/21 22:04:38  stolcke
-#    support for MacOSX
-#
-#    Revision 1.5  2002/07/09 15:06:17  stolcke
-#    handle i386-solaris case
-#
-#    Revision 1.4  2002/02/11 08:26:43  stolcke
-#    detect cygwin platform
-#
-#    Revision 1.3  1999/10/22 08:29:18  stolcke
-#    fixed syntax errors
-#    removed reference to DECIPHER
-#    recognizer IRIX6 systems
-#
-#    Revision 1.2  1999/02/20 07:15:40  stolcke
-#    added support for linux/i686
-#
-# Revision 1.2  1995/04/22  03:25:34  stolcke
-# use 'uname -m' (hardware name) to determine cpu type
-# (since the same OS may in fact support several cpu types)
-#
-# Revision 1.1  1995/04/22  01:06:00  tmk
-# Initial revision
-#
+#    RCS ID: $Id: machine-type,v 1.11 2011/10/21 21:25:58 stolcke Exp $
 #
 
 ##    NOTE:  (tmk 950414)
@@ -67,59 +29,63 @@
 ##	  and leaves the MACHINE_TYPE variable defined as a null string.
 
 
-set RESULT = (`uname -a`)
+set -- `uname -a`
 
-if ($#RESULT > 0) then
-    if ($RESULT[5] =~ IP*) then	# "IP" is an irix processor
-	if ($RESULT[3] =~ 4.*) then
-	    set MACHINE_TYPE = mips
-	else if ($RESULT[3] =~ [56].*) then
-            set MACHINE_TYPE = mips-elf
-	else
-	    ## Generate an error by doing nothing.  (Used to be the line below:)
-	    ## echo "ERROR: Unsupported machine type: "$RESULT  
-	endif
-    else if ($RESULT[5] =~ sun4*) then
-
-#	set MACHINE_TYPE = sparc
-
-	if ($RESULT[3] =~ 4.*) then
-	    set MACHINE_TYPE = sparc
-	else if ($RESULT[3] =~ 5.*) then
-	    set MACHINE_TYPE = sparc-elf
-	else
-	    ## Generate an error by doing nothing.  (Used to be the line below:)
-	    ## echo "ERROR: Unsupported machine type: "$RESULT
-	endif
-    else if ($RESULT[5] == i86pc) then
-	set MACHINE_TYPE = i386-solaris
-    else if ($RESULT[5] == alpha) then
-	set MACHINE_TYPE = alpha
-    else if (`uname -m` == ppc64) then
-	set MACHINE_TYPE = ppc64
-    else if (`uname -s` =~ CYGWIN*) then
-	set MACHINE_TYPE = cygwin
-    else if (`uname -s` =~ FreeBSD*) then
-	set MACHINE_TYPE = freebsd
-    else if (`uname -s` == Darwin) then
-	set MACHINE_TYPE = macosx
-    else if (`uname -m` == i686) then
-	set MACHINE_TYPE = i686
-    else if (`uname -m` == x86_64) then
-	#set MACHINE_TYPE = i686-m64
-	set MACHINE_TYPE = i686
-    else
-	## Generate an error by doing nothing.  (Used to be the line below:)
-	## echo "ERROR: Unsupported machine type: "$RESULT
-    endif
-else
-    ## Generate an error by doing nothing.  (Used to be the line below:)
-    ## echo "ERROR: Unsupported machine type: "$RESULT
-endif
+if [ $# -gt 0 ]; then
+    case "$5" in
+    IP*)    # "IP" is an Iris processor
+	    case $3 in
+	    4.*)    MACHINE_TYPE=mips
+		    ;;
+	    [56].*) MACHINE_TYPE=mips-elf
+		    ;;
+	    esac
+	    ;;
+    sun4*)
+	    case $3 in
+	    4.*)    MACHINE_TYPE=sparc
+		    ;;
+	    5.*)    MACHINE_TYPE=sparc-elf
+		    ;;
+	    esac
+	    ;;
+    i86pc)	MACHINE_TYPE=i386-solaris
+	    ;;
+    alpha)	MACHINE_TYPE=alpha
+	    ;;
+    *)
+	    case "`uname -s`" in
+	    CYGWIN*)	MACHINE_TYPE=cygwin
+			;;
+	    FreeBSD*)	MACHINE_TYPE=freebsd
+			;;
+	    Darwin)	MACHINE_TYPE=macosx
+			;;
+	    *)
+		case "`uname -m`" in
+		ppc64)	MACHINE_TYPE=ppc64
+			;;
+		i686)	MACHINE_TYPE=i686
+			;;
+		x86_64) #MACHINE_TYPE=i686-m64
+			MACHINE_TYPE=i686
+			;;
+		esac
+		;;
+	    esac
+	    ;;
+    esac
+fi
 
 ## NOTE:  If we couldn't figure out the MACHINE_TYPE by this point, the
 ##        following line generates an error, rather than returning a
 ##	  string containing the word "ERROR".  This is still not great 
 ##	  error handling, but it's slightly better.  
 
-echo $MACHINE_TYPE
+if [ -z "$MACHINE_TYPE" ]; then
+    echo "could not determine MACHINE_TYPE"
+    exit 1
+else
+    echo $MACHINE_TYPE
+fi
+
