1.5.12

diff --git a/utils/src/make-big-lm b/utils/src/make-big-lm
--- a/utils/src/make-big-lm
+++ b/utils/src/make-big-lm
@@ -13,7 +13,7 @@
 #	  into memory.
 #	- ngram-counts loads only those counts exceeding cutoff values.
 #
-# $Header: /home/srilm/devel/utils/src/RCS/make-big-lm,v 1.15 2005/01/05 23:46:10 stolcke Exp $
+# $Header: /home/srilm/devel/utils/src/RCS/make-big-lm,v 1.23 2010/08/21 07:55:09 stolcke Exp $
 #
 
 name=biglm
@@ -47,9 +47,16 @@ kndiscount8=0
 kndiscount9=0
 using_kn=
 max_per_file=10000000
+ngram_filter=cat
+subset_filter=cat
+counts=
+test_data=
 
 trust_totals=0
 metatag=__meta__	# lowercase so it works with ngram-count -tolower
+
+# avoid locale problems with gawk script computing discounting parameters
+LC_NUMERIC=C; export LC_NUMERIC
 
 while [ $# -gt 0 ]; do
     case "$1" in
@@ -64,15 +71,15 @@ while [ $# -gt 0 ]; do
     -gt7min)	gt7min=$2; options="$options $1 $2" ; shift ;;
     -gt8min)	gt8min=$2; options="$options $1 $2" ; shift ;;
     -gt9min)	gt9min=$2; options="$options $1 $2" ; shift ;;
-    -gt1max)	gt1max=$2; shift ;;
-    -gt2max)	gt2max=$2; shift ;;
-    -gt3max)	gt3max=$2; shift ;;
-    -gt4max)	gt4max=$2; shift ;;
-    -gt5max)	gt5max=$2; shift ;;
-    -gt6max)	gt6max=$2; shift ;;
-    -gt7max)	gt7max=$2; shift ;;
-    -gt8max)	gt8max=$2; shift ;;
-    -gt9max)	gt9max=$2; shift ;;
+    -gt1max)	gt1max=$2; using_gt=1; shift ;;
+    -gt2max)	gt2max=$2; using_gt=1; shift ;;
+    -gt3max)	gt3max=$2; using_gt=1; shift ;;
+    -gt4max)	gt4max=$2; using_gt=1; shift ;;
+    -gt5max)	gt5max=$2; using_gt=1; shift ;;
+    -gt6max)	gt6max=$2; using_gt=1; shift ;;
+    -gt7max)	gt7max=$2; using_gt=1; shift ;;
+    -gt8max)	gt8max=$2; using_gt=1; shift ;;
+    -gt9max)	gt9max=$2; using_gt=1; shift ;;
     -kndiscount1)	kndiscount1=1; using_kn=1 ;;
     -kndiscount2)	kndiscount2=1; using_kn=1 ;;
     -kndiscount3)	kndiscount3=1; using_kn=1 ;;
@@ -86,17 +93,37 @@ while [ $# -gt 0 ]; do
 			kndiscount4=1; kndiscount5=1; kndiscount6=1;
 			kndiscount7=1; kndiscount8=1; kndiscount9=1;
 			using_kn=1 ;;
-    -read)	if [ "$2" = - -o "$2" = "/dev/stdin" ]; then
+    -wbdiscount)	using_wb=1 ;;
+    -wbdiscount*|-ukndiscount*|-cdiscount*|-ndiscount*|-addsmooth*)
+		echo "$0: must use one of GT, KN, or WB discounting for all orders" >&2
+		exit 2 ;;
+    -read)	if [ "$2" = "" -o "$2" = - -o "$2" = "/dev/stdin" ]; then
 			echo "$0: cannot read from stdin" >&2
 			exit 2
 		fi
 		counts="$counts $2" ; shift ;;
     -trust-totals) trust_totals=1 ;;
     -max-per-file) max_per_file=$2 ; shift ;;
+    -ngram-filter) ngram_filter="$2" ; shift ;;
+    -text)	test_data="$2"; shift ;;
     *)		options="$options $1" ;;
     esac
     shift
 done
+
+if [ -z "$counts" ]; then
+    echo "No counts specified" >&2
+    echo "usage: $0 -read COUNTS [-name PATH] [-text TESTSET] [-ngram-filter FILTER] [-max-per-file N] [ngram-count-options ...]" >&2
+    exit 2
+fi
+
+if [ -n "$using_gt" -a -n "$using_kn" -o \
+     -n "$using_gt" -a -n "$using_wb" -o \
+     -n "$using_kn" -a -n "$using_wb" ]
+then
+    echo "$0: cannot mix GT, KN, and WB discounting" >&2
+    exit 2
+fi
 
 if [ $trust_totals -eq 0 ]; then
     options="$options -meta-tag $metatag"
@@ -118,9 +145,13 @@ if [ "$using_kn" ]; then
     kncounts=$name.kncounts.gz
     if [ -f $kncounts ]; then
 	echo "using existing $kncounts" >&2
+    elif [ $order -eq 1 ]; then
+    	# create a dummy empty file
+	gzip -f < /dev/null > $kncounts
     else
 	mkdir -p $name.kndir 
-	gunzip -cf $counts | \
+	gzip -dcf $counts | \
+	eval "$ngram_filter" | \
 	(set -x; make-kn-counts \
 		no_max_order=1 max_per_file=$max_per_file \
 		order=$order \
@@ -143,22 +174,31 @@ fi
 #
 # compute counts-of-counts
 #
-if [ -f $name.gt${order}counts ]; then
+if [ "$using_wb" ]; then
+    :
+elif [ -f $name.gt${order}counts ]; then
     echo "using existing gtcounts" >&2 
 else
     if [ "$using_kn" ]; then
 	# concatenate KN modified counts with highest-order original counts
-	gunzip -c $kncounts | gawk 'NF < 1+'$order
-	gunzip -cf $counts | gawk 'NF == 1+'$order
+	# Note: even though $kncounts ends in .gz it might be a plain file
+	# if platform doesn't support gzip pipes, so use gzip -df .
+	gzip -dcf $kncounts | gawk 'NF < 1+'$order
+	gzip -dcf $counts | eval "$ngram_filter" | gawk 'NF == 1+'$order
     else 
-        gunzip -cf $counts
+        gzip -dcf $counts | eval "$ngram_filter"
     fi | (set -x; get-gt-counts out=$name max=20 maxorder=$order)
 fi
 
 #
 # compute discount factors
 #
-gtflags=
+if [ "$using_wb" ]; then
+    # apply WB discount to all ngram orders
+    gtflags=-wbdiscount
+else
+    gtflags=
+fi
 for n in 1 2 3 4 5 6 7 8 9 
 do
     if [ $n -le $order -a -f $name.gt${n}counts ]; then
@@ -175,18 +215,33 @@ do
     fi
 done
 
+# if test data is specified compute context ngrams
+if [ -n "$test_data" -a $order -gt 1 ]; then
+    order1=`expr $order - 1`
+    (set -x; \
+    ngram-count -order $order1 -text "$test_data" -sort -write $name.contexts)
+
+    # ... and filter the ngrams to contain only the required contexts
+    subset_filter="subset-context-ngrams contexts=$name.contexts"
+fi
+
 #
 # filter counts and build lm
 #
 if [ "$using_kn" ]; then
     # concatenate KN modified counts with highest-order original counts
-    gunzip -c $kncounts | gawk 'NF < 1+'$order
-    gunzip -cf $counts | gawk 'NF == 1+'$order
+    # Note: even though $kncounts ends in .gz it might be a plain file
+    # if platform doesn't support gzip pipes, so use gzip -df .
+    gzip -dcf $kncounts | gawk 'NF < 1+'$order
+    gzip -dcf $counts | eval "$ngram_filter" | gawk 'NF == 1+'$order
 else 
-    gunzip -cf $counts
+    gzip -dcf $counts | eval "$ngram_filter"
 fi | \
+eval "$subset_filter" | \
 (set -x;  \
 ngram-count -read - -read-with-mincounts -order $order \
 	$gtflags \
 	$options)
+
+rm -f $name.contexts
 
